use Mix.Config

port = String.to_integer(System.get_env("PORT") || "4000")
# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :wordplay, WordplayWeb.Endpoint,
  url: [host: System.get_env("HOST") || "localhost", port: port],
  http: [
    port: port,
    transport_options: [socket_opts: [:inet6]]
  ],
  cache_static_manifest: "priv/static/cache_manifest.json",
  server: true

# Do not print debug messages in production
config :logger, level: String.to_atom(System.get_env("LOG_LEVEL") || "info")

# ## Using releases (Elixir v1.9+)
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start each relevant endpoint:
#
# config :wordplay, WordplayWeb.Endpoint, server: true
